---
title: "Projet stat pour données environnementales"
author: "Louis Delignac, Baptiste Gerbouin, Théo Lavandier, Alexandre Leys, Hamad Tria"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    df_print: kable
    highlight: tango
---

```{r setup, message=FALSE, echo=FALSE}
# install.packages("tidyverse")
library(tidyverse)
library(ggplot2)
library(kableExtra)
library(sf)
library(ggspatial)
```

```{r}
oiseaux <- read.csv("data/Oiseaux_up_to_2023.csv", header = TRUE, sep = "\t")
LUP <- read.csv("data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)
```

```{r}
# CREATE A NEW COLUMN IN THE OISEAUX DATAFRAME THAT CONTAINS THE LATIN NAME OF THE BIRD
# THE LATIN NAME IS THE FIRST NAME IN THE "Nom_Taxon_Cite" COLUMN
# IF THE NAME CONTAINS A "|", THE LATIN NAME IS THE FIRST NAME BEFORE THE "|"

# Split the names
my_split <- function(array, str = " \\| ") {
  out <- rep(NA, length(array))
  for (i in 1:length(array)) {
    out[i] <- unlist(strsplit(array[i], str))[1]
  }
  return (out)
}

# Test the function
only_latin <- my_split(as.vector(oiseaux$Nom_Taxon_Cite))
length(unique(only_latin)) == length(unique(oiseaux$Code_Ref))

# Add the new column to the dataframe
oiseaux$latin <- only_latin
```

```{r}
# THE MOST FREQUENT BIRD SPECIES OBSERVED IN THE DATASET
as.data.frame(sort(table(oiseaux$latin), decreasing = TRUE)[1:10])
```


```{r}
oiseaux$annee <- as.numeric(substr(oiseaux$Date, 1, 4))
```

```{r}
deombrement <- oiseaux %>%
  group_by(Code_Maille, latin, annee) %>%
  summarise(sum = sum(Denombrement_min, na.rm = TRUE), .groups = 'drop') %>%
  arrange(desc(sum))

p <- deombrement$sum / sum(deombrement$sum)

p
```

```{r}
# P pae 
```












```{r}
# FREQUENCY OF BIRD SPECIES OBSERVED IN THE DATASET BY YEAR
Annee <- my_split(as.vector(oiseaux$Date), str = "-")
oiseaux$Annee <- as.factor(Annee)
as.data.frame.matrix(table(oiseaux$latin, oiseaux$Annee))
```

```{r}
# CREATE A NEW COLUMN IN THE OISEAUX DATAFRAME THAT CONTAINS THE MOS11 VALUE OF THE POINT
filter <- LUP$BufferSize == 500
LUP_500_MOS11 <- LUP[filter,c("Geometry", "ID", "X", "Y", "BufferSize", "MOS11")]
rownames(LUP_500_MOS11) <- 1:nrow(LUP_500_MOS11)
LUP_500_MOS11[, c("ID","MOS11")]

MOS11 <- rep(NA, nrow(oiseaux))
for (i in 1:nrow(oiseaux)) {
  MOS11[i] <- which(oiseaux$Code_Maille[i] == LUP_500_MOS11$ID)
}

# Add the new column to the dataframe
oiseaux$MOS11 <- LUP_500_MOS11$MOS11[MOS11]
```

```{r}
# THE NUMBER OF BIRDS OBSERVED IN EACH MOS11 AREA BY YEAR
data <- oiseaux %>%
  group_by(Code_Maille, Annee, MOS11) %>%
  select(Denombrement_min) %>% 
  summarise(sum = sum(Denombrement_min, na.rm = TRUE))

ggplot(data, aes(x=MOS11, y=sum, color=Annee)) +
      geom_point(size=2) 
```


```{r}
### TOTAL NUMBER OF OBSERVATIONS BY ZONE

biodiver_sites <- read.csv("data/BiodiverCite_sites.csv", header = TRUE, sep = ';')
LUP <- read.csv("data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)
oiseaux <- read.csv("data/Oiseaux_up_to_2023.csv", header = TRUE, sep = "\t")

merged_data <- merge(biodiver_sites, LUP, by.x = "code_site", by.y = "ID", all = TRUE)

merged_data <- merge(merged_data, oiseaux, by.x = "code_site", by.y = "Code_Maille", all = TRUE)

coordinates <- st_as_sf(merged_data, coords = c("X.y", "Y"), crs = 2154)
coordinates <- st_transform(coordinates, crs = 4326)

total_observations <- coordinates %>%
  group_by(code_site) %>%
  summarise(n = n())

ggplot(data = total_observations) +
  annotation_map_tile() +  
  geom_sf(aes(size = n), color = 'blue', alpha = 0.5) +
  scale_size_continuous(range = c(2, 12), 
                        breaks = c(1, 100, 200, 500, 1000), 
                        labels = c("1", "100", "200", "500", "1000")) +
  labs(title = 'Nombre total d\'observations par zone d\'observation',
       size = 'Nombre d\'observations') +
  theme_minimal() +
  guides(size = guide_legend(override.aes = list(alpha = 0.5)))

```

```{r}
# Noms des espèces les plus observes  par catégorie de vent
merged_data$Nom_Latin <- sapply(strsplit(merged_data$Nom_Taxon_Cite, " \\| "), `[`, 1)

species_by_wind <- merged_data %>%
  group_by(Vent, Nom_Latin) %>%
  summarise(count = n()) %>%
  arrange(Vent, desc(count))

top_species_by_wind <- species_by_wind %>%
  group_by(Vent) %>%
  slice_max(order_by = count, n = 1) %>%
  ungroup()

top_species_by_wind

```

```{r}
# Noms des espèces les plus observes  par nom de site

species_by_site <- merged_data %>%
  group_by(name_site, Nom_Latin) %>%
  summarise(count = n()) %>%
  arrange(name_site, desc(count))

top_species_by_site <- species_by_site %>%
  group_by(name_site) %>%
  slice_max(order_by = count, n = 1) %>%
  ungroup()

top_species_by_site

```


```{r}
# Noms des espèces les plus observes  par temperature

species_by_temperature <- merged_data %>%
  group_by(Temperature, Nom_Latin) %>%
  summarise(count = n()) %>%
  arrange(Temperature, desc(count))

top_species_by_temperature <- species_by_temperature %>%
  group_by(Temperature) %>%
  slice_max(order_by = count, n = 1) %>%
  ungroup()

top_species_by_temperature
```


