---
title: "Projet stat pour données environnementales"
author: "Louis Delignac, Baptiste Gerbouin, Théo Lavandier, Alexandre Leys, Hamad Tria"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    df_print: kable
    highlight: tango
---

```{r setup, message=FALSE, echo=FALSE}
# install.packages("tidyverse")
library(tidyverse)
library(ggplot2)
library(kableExtra)
library(sf)
library(ggspatial)
```

```{r}
oiseaux <- read.csv("data/Oiseaux_up_to_2023.csv", header = TRUE, sep = "\t")
LUP <- read.csv("data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)
```

```{r}
# CREATE A NEW COLUMN IN THE OISEAUX DATAFRAME THAT CONTAINS THE LATIN NAME OF THE BIRD
# THE LATIN NAME IS THE FIRST NAME IN THE "Nom_Taxon_Cite" COLUMN
# IF THE NAME CONTAINS A "|", THE LATIN NAME IS THE FIRST NAME BEFORE THE "|"

# Split the names
my_split <- function(array, str = " \\| ") {
  out <- rep(NA, length(array))
  for (i in 1:length(array)) {
    out[i] <- unlist(strsplit(array[i], str))[1]
  }
  return (out)
}

# Test the function
only_latin <- my_split(as.vector(oiseaux$Nom_Taxon_Cite))
length(unique(only_latin)) == length(unique(oiseaux$Code_Ref))

# Add the new column to the dataframe
oiseaux$latin <- only_latin
```

```{r}
# THE MOST FREQUENT BIRD SPECIES OBSERVED IN THE DATASET
as.data.frame(sort(table(oiseaux$latin), decreasing = TRUE)[1:10])
```

```{r}
# FREQUENCY OF BIRD SPECIES OBSERVED IN THE DATASET BY YEAR
Annee <- my_split(as.vector(oiseaux$Date), str = "-")
oiseaux$Annee <- as.factor(Annee)
as.data.frame.matrix(table(oiseaux$latin, oiseaux$Annee))
```

```{r}
# CREATE A NEW COLUMN IN THE OISEAUX DATAFRAME THAT CONTAINS THE MOS11 VALUE OF THE POINT
filter <- LUP$BufferSize == 500
LUP_500_MOS11 <- LUP[filter,c("Geometry", "ID", "X", "Y", "BufferSize", "MOS11")]
rownames(LUP_500_MOS11) <- 1:nrow(LUP_500_MOS11)
LUP_500_MOS11[, c("ID","MOS11")]

MOS11 <- rep(NA, nrow(oiseaux))
for (i in 1:nrow(oiseaux)) {
  MOS11[i] <- which(oiseaux$Code_Maille[i] == LUP_500_MOS11$ID)
}

# Add the new column to the dataframe
oiseaux$MOS11 <- LUP_500_MOS11$MOS11[MOS11]
```

```{r}
# THE NUMBER OF BIRDS OBSERVED IN EACH MOS11 AREA BY YEAR
data <- oiseaux %>%
  group_by(Code_Maille, Annee, MOS11) %>%
  select(Denombrement_min) %>% 
  summarise(sum = sum(Denombrement_min, na.rm = TRUE))

ggplot(data, aes(x=MOS11, y=sum, color=Annee)) +
      geom_point(size=2) 
```


```{r}
### TOTAL NUMBER OF OBSERVATIONS BY ZONE

biodiver_sites <- read.csv("data/BiodiverCite_sites.csv", header = TRUE, sep = ';')
LUP <- read.csv("data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)
oiseaux <- read.csv("data/Oiseaux_up_to_2023.csv", header = TRUE, sep = "\t")

merged_data <- merge(biodiver_sites, LUP, by.x = "code_site", by.y = "ID", all = TRUE)

merged_data <- merge(merged_data, oiseaux, by.x = "code_site", by.y = "Code_Maille", all = TRUE)

coordinates <- st_as_sf(merged_data, coords = c("X.y", "Y"), crs = 2154)
coordinates <- st_transform(coordinates, crs = 4326)

total_observations <- coordinates %>%
  group_by(code_site) %>%
  summarise(n = n())

ggplot(data = total_observations) +
  annotation_map_tile() +  
  geom_sf(aes(size = n), color = 'blue', alpha = 0.5) +
  scale_size_continuous(range = c(2, 12), 
                        breaks = c(1, 100, 200, 500, 1000), 
                        labels = c("1", "100", "200", "500", "1000")) +
  labs(title = 'Nombre total d\'observations par zone d\'observation',
       size = 'Nombre d\'observations') +
  theme_minimal() +
  guides(size = guide_legend(override.aes = list(alpha = 0.5)))

```
```{r}
# On va faire une carte leaflet pour visualiser chaque zone en fonction de sa buffer size
library(leaflet)

LUP <- read.csv("data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)

# LUP contient chaque zone d'observation. On a ses coordonnées, et sa buffersize.
# Les coordonnées sont dans les colonnes X et Y, et la buffersize dans la colonne BufferSize. 
# Il faut d'abord convertir les coordonnées en coordonnées géographiques (latitude et longitude)

coordinates <- st_as_sf(LUP, coords = c("X", "Y"), crs = 2154)
coordinates <- st_transform(coordinates, crs = 4326)

#ON prend que les coordinates avec BufferSize = 500
coordinates <- coordinates[coordinates$BufferSize == 500,]

# On va maintenant créer une carte leaflet pour visualiser chaque zone d'observation
pal <- colorNumeric("viridis", domain = coordinates$MOS11)

leaflet(data = coordinates) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircles(radius = 300, color = ~pal(MOS11), fillOpacity = 0.5) %>%
  addLegend("bottomright", pal = pal, values = coordinates$MOS11, title = "MOS11") %>%
  addScaleBar(position = "bottomleft")
```

```{r}
coordinates




```



```{r}
# Noms des espèces les plus observes  par catégorie de vent
merged_data$Nom_Latin <- sapply(strsplit(merged_data$Nom_Taxon_Cite, " \\| "), `[`, 1)

species_by_wind <- merged_data %>%
  group_by(Vent, Nom_Latin) %>%
  summarise(count = n()) %>%
  arrange(Vent, desc(count))

top_species_by_wind <- species_by_wind %>%
  group_by(Vent) %>%
  slice_max(order_by = count, n = 1) %>%
  ungroup()

top_species_by_wind

```

```{r}
# Noms des espèces les plus observes  par nom de site

species_by_site <- merged_data %>%
  group_by(name_site, Nom_Latin) %>%
  summarise(count = n()) %>%
  arrange(name_site, desc(count))

top_species_by_site <- species_by_site %>%
  group_by(name_site) %>%
  slice_max(order_by = count, n = 1) %>%
  ungroup()

top_species_by_site

```




```{r}
# Noms des espèces les plus observes  par temperature

species_by_temperature <- merged_data %>%
  group_by(Temperature, Nom_Latin) %>%
  summarise(count = n()) %>%
  arrange(Temperature, desc(count))

top_species_by_temperature <- species_by_temperature %>%
  group_by(Temperature) %>%
  slice_max(order_by = count, n = 1) %>%
  ungroup()

top_species_by_temperature
```


## On doit analyser les pics de diversité par zone MOS

```{r}
# On compte le nombre d'espece differentes (espece uniques), à chaque valeur differente de la colonne MOS 11

# On regroupe les valeurs de la colonne MOS11 dans des intervalles tous les 0.1 pour faciliter le groupement par la suite. On fait ça avec le dataframe merfe_data, sans modifier la valeur MOS11 de merged data

# On crée une nouvelle colonne MOS11_interval dans le dataframe merged_data

merged_data$MOS11_interval <- cut(merged_data$MOS11, breaks = seq(0, 1, by = 0.1), include.lowest = TRUE)

# On compte le nombre d'espece unique par intervalle de MOS11

species_by_MOS11 <- merged_data %>%
  group_by(MOS11_interval) %>%
  summarise(n_species = n_distinct(Nom_Latin))

# On affiche le nombre d'espece unique par intervalle de MOS11

ggplot(data = species_by_MOS11) +
  geom_bar(aes(x = MOS11_interval, y = n_species), stat = "identity") +
  labs(title = 'Nombre d\'espèces uniques par intervalle de MOS11',
       x = 'MOS11',
       y = 'Nombre d\'espèces uniques') +
  theme_minimal()

```

```{r}
# On créer une fonction qui calcule l'indice de Shannon 

shannon_index <- function(x) {
  p <- x / sum(x)
  exp(-sum(p * log(p)))
}

# sachant qu'on le nombre d'observation dans la colonne denombrement_min, calculons l'indice de Shannon pour chaque zonne Nom_lieu

shannon_by_site <- merged_data %>%
  group_by(name_site) %>%
  summarise(shannon = shannon_index(Denombrement_min))

# Chaque lieu correspond à une valeur de MOS11, on peut donc afficher l'indice de Shannon en fonction de MOS11. On reprend donc les valeurs qu'on a calculer pour chaque lieu et on les fait correspondre à la valeur de MOS11

shannon_by_MOS11 <- merged_data %>%
  group_by(MOS11) %>%
  summarise(shannon = shannon_index(Denombrement_min))

# On drop les NA

shannon_by_MOS11 <- shannon_by_MOS11[!is.na(shannon_by_MOS11$shannon), ]

# On fait la moeyyenne des indices sur des intervalles de MOS11 tous les 0.1

shannon_by_MOS11$MOS11_interval <- cut(shannon_by_MOS11$MOS11, breaks = seq(0, 1, by = 0.1), include.lowest = TRUE)

shannon_by_MOS11 <- shannon_by_MOS11 %>%
  group_by(MOS11_interval) %>%
  summarise(shannon = mean(shannon))

# On affiche l'indice de Shannon en fonction de MOS11 avec un barchart

ggplot(data = shannon_by_MOS11) +
  geom_bar(aes(x = MOS11_interval, y = shannon), stat = "identity") +
  labs(title = 'Indice de Shannon par intervalle de MOS11',
       x = 'MOS11',
       y = 'Indice de Shannon') +
  theme_minimal()

```

```{r}

# On prend les 4 premiers charactères de la colonne date pour extraire l'année

merged_data$year <- as.numeric(substr(merged_data$date, 1, 4))


shannon_by_site2018 <- merged_data %>%
  filter(year == 2018) %>%
  group_by(name_site) %>%
  summarise(shannon = shannon_index(Denombrement_min))

shannon_by_MOS11_2018 <- merged_data %>%
  filter(year == 2018) %>%
  group_by(MOS11) %>%
  summarise(shannon = shannon_index(Denombrement_min))

shannon_by_MOS11_2018 <- shannon_by_MOS11_2018[!is.na(shannon_by_MOS11_2018$shannon), ]

shannon_by_MOS11_2018$MOS11_interval <- cut(shannon_by_MOS11_2018$MOS11, breaks = seq(0, 1, by = 0.1), include.lowest = TRUE)

shannon_by_MOS11_2018 <- shannon_by_MOS11_2018 %>%
  group_by(MOS11_interval) %>%
  summarise(shannon = mean(shannon))


ggplot(data = shannon_by_MOS11_2018) +
  geom_bar(aes(x = MOS11_interval, y = shannon), stat = "identity") +
  labs(title = 'Indice de Shannon par intervalle de MOS11 en 2018',
       x = 'MOS11',
       y = 'Indice de Shannon') +
  theme_minimal()

```

```{r}
# On a observé que le pic de diversité se situe entre 0.2 et 0.4 MOS11, on va donc s'intéresser à cette zone

# On commence par load les données de caractistiques des espèces d'oiseaux

bird_data <- read_csv('data/traits-statut-IUCN-biodivercite.csv')

# On merge les données de traits avec les données de dénombrement (la colonne nom s'appelle Nom latin pour bird data)

merged_data <- left_join(merged_data, bird_data, by = c('Nom_Latin' = 'Nom latin'))





```
```{r}
merged_data <- merged_data %>%
  rename(Niveau_de_specialisation = `Niveau de spécialisation`)
```



```{r}

# On normalise les données des observations par site afin que chaque site soit comparable. Pour ce faire on va tout convertir en pourcentage de l'observation par site. 

merged_data <- merged_data %>%
  group_by(name_site) %>%
  mutate(Denombrement_min_norm = Denombrement_min / sum(Denombrement_min))

## On supprime les NA de la colonne Denombrement_min_norm

merged_data <- merged_data[!is.na(merged_data$Denombrement_min_norm), ]

## On supprime les NA de la colonne Niveau_de_specialisation

merged_data <- merged_data[!is.na(merged_data$Niveau_de_specialisation), ]

# On plot les valeurs normalisées en fonction de MOS11

ggplot(data = merged_data) +
  geom_point(aes(x = MOS11, y = Denombrement_min_norm, color = Niveau_de_specialisation)) +
  labs(title = 'Dénombrement normalisé en fonction de MOS11',
       x = 'MOS11',
       y = 'Dénombrement normalisé') +
  theme_minimal()

```

```{r}

# Maintenant qu'on a la colonne denombrement_min_norm on peut faire la densité des oiseaux en fonction de MOS11 par rapport à cette variable

ggplot(data = merged_data) +
  geom_density(aes(x = MOS11, color = Niveau_de_specialisation), fill = 'blue', alpha = 0.5) +
  labs(title = 'Densité des oiseaux en fonction de MOS11',
       x = 'MOS11',
       y = 'Densité') +
  theme_minimal()

```

```{r}


# On refait la densité en rajoutant en poid aux observations avec la colonne denombrement_min_norm qui correspond au nombre d'observation normalisé par site

ggplot(data = merged_data) +
  geom_density(aes(x = MOS11, color = Niveau_de_specialisation, weight = Denombrement_min_norm), fill = 'blue', alpha = 0.5) +
  labs(title = 'Densité des oiseaux en fonction de MOS11',
       x = 'MOS11',
       y = 'Densité') +
  theme_minimal()

```





```{r}

merged_data$MOS11 <- as.numeric(merged_data$MOS11)

ggplot(data = merged_data, aes(x = MOS11, y = Denombrement_min_norm, color = Niveau_de_specialisation)) +
  geom_density_2d(alpha = 0.5) +
  labs(title = 'Évolution de la spécialisation en fonction de MOS11',
       x = 'MOS11',
       y = 'Pourcentage d\'observations',
       color = 'Niveau de spécialisation') +
  theme_minimal()


```


```{r}
ggplot(data = merged_data, aes(x = MOS11, y = Denombrement_min_norm, fill = Niveau_de_specialisation)) +
  geom_violin() +
  labs(title = 'Évolution de la spécialisation en fonction de MOS11',
       x = 'MOS11',
       y = 'Pourcentage d\'observations',
       fill = 'Niveau de spécialisation') +
  theme_minimal()



```




```{r}

# On fait la courbe de densité des oiseaux en fonction de MOS11, avec les oiseaux de Niveau de spécialisation qui vaut Generaliste

# On renome Niveau de spécialisation en Niveau_de_specialisation


ggplot(data = merged_data %>% filter(Niveau_de_specialisation == 'Généraliste')) +
  geom_density(aes(x = MOS11), fill = 'blue', alpha = 0.5) +
  labs(title = 'Densité des oiseaux Généralistes en fonction de MOS11',
       x = 'MOS11',
       y = 'Densité') +
  theme_minimal()

```

```{r}

ggplot(data = merged_data %>% filter(Niveau_de_specialisation == 'Bâti')) +
  geom_density(aes(x = MOS11), fill = 'blue', alpha = 0.5) +
  labs(title = 'Densité des oiseaux de type Bâti en fonction de MOS11',
       x = 'MOS11',
       y = 'Densité') +
  theme_minimal()


```

```{r}

ggplot(data = merged_data %>% filter(Niveau_de_specialisation == 'Forêt')) +
  geom_density(aes(x = MOS11), fill = 'blue', alpha = 0.5) +
  labs(title = 'Densité des oiseaux de type Forêt en fonction de MOS11',
       x = 'MOS11',
       y = 'Densité') +
  theme_minimal()

```


```{r}

```


