---
title: "Projet stat pour données environnementales"
author: "Louis Delignac, Baptiste Gerbouin, Théo Lavandier, Alexandre Leys, Hamad Tria"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    df_print: kable
    highlight: tango
---

```{r setup, message=FALSE, echo=FALSE}
# install.packages("tidyverse")
library(tidyverse)
library(ggplot2)
library(kableExtra)
library(sf)
library(ggspatial)
```


```{r}
oiseaux <- read.csv("data/Oiseaux_up_to_2023.csv", header = TRUE, sep = "\t")
# CREATE A NEW COLUMN IN THE OISEAUX DATAFRAME THAT CONTAINS THE LATIN NAME OF THE BIRD
my_split <- function(array, str = " \\| ") {
  out <- rep(NA, length(array))
  for (i in 1:length(array)) {
    out[i] <- unlist(strsplit(array[i], str))[1]
  }
  return (out)
}

only_latin <- my_split(as.vector(oiseaux$Nom_Taxon_Cite))
# length(unique(only_latin)) == length(unique(oiseaux$Code_Ref))

oiseaux$latin <- only_latin
oiseaux$annee <- as.numeric(substr(oiseaux$Date, 1, 4))
```



```{r}
# THE MOST FREQUENT BIRD SPECIES OBSERVED IN THE DATASET
as.data.frame(sort(table(oiseaux$latin), decreasing = TRUE)[1:10])
```

```{r}
# FREQUENCY OF BIRD SPECIES OBSERVED IN THE DATASET BY YEAR
Annee <- my_split(as.vector(oiseaux$Date), str = "-")
oiseaux$Annee <- as.factor(Annee)
as.data.frame.matrix(table(oiseaux$latin, oiseaux$Annee))
```




```{r}
## Analyse de diversité par rapport à MOS11 et par année

denombrement <- oiseaux %>%
  group_by(Code_Maille, annee, latin) %>%
  summarise(sum = sum(Denombrement_min, na.rm = TRUE), .groups = 'drop') %>%
  arrange(desc(Code_Maille))

denombrement$p <- rep(NA, nrow(denombrement))
for (i in 1:nrow(denombrement)) {
  numerator <- denombrement$sum[i]
  denominator <- 
    sum(denombrement$sum[which(denombrement$Code_Maille == denombrement$Code_Maille[i] 
                               & denombrement$annee == denombrement$annee[i])])
  denombrement$p[i] <- numerator / denominator
}

index <- denombrement %>%
  group_by(Code_Maille, annee = factor(annee)) %>%
  summarise(D1 = sum(p > 0, na.rm = TRUE), 
            D2 = exp(-sum(p*log(p))), 
            D3 = 1 / sum(p^2), .groups = 'drop') %>%
  arrange(desc(Code_Maille))

LUP <- read.csv("data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)
index$MOS11 <- rep(NA, nrow(index))
for (i in 1:nrow(index)) {
  index$MOS11[i] <- LUP$MOS11[which(index$Code_Maille[i] == LUP$ID & LUP$BufferSize == 500)]
}

par(mfrow = c(1, 3))
ggplot(index, aes(x = MOS11, y = D1, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D1 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot(index, aes(x = MOS11, y = D2, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D2 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot(index, aes(x = MOS11, y = D3, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D3 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r}
ggplot(index, aes(x = MOS11, y = D1, color = as.factor(annee))) +
  geom_point(size = 2) +
  geom_smooth(method = "auto", se = TRUE, color = "black", alpha = 0.2) +
  labs(title = 'D1 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot(index, aes(x = MOS11, y = D2, color = as.factor(annee))) +
  geom_point(size = 2) +
  geom_smooth(method = "auto", se = TRUE, color = "black", alpha = 0.2) +
  labs(title = 'D2 en fonction de MOS11',
       x = 'MOS11',
       y = 'D2') +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot(index, aes(x = MOS11, y = D3, color = as.factor(annee))) +
  geom_point(size = 2) +
  geom_smooth(method = "auto", se = TRUE, color = "black", alpha = 0.2) +
  labs(title = 'D3 en fonction de MOS11',
       x = 'MOS11',
       y = 'D3') +
  theme_minimal() +
  theme(legend.position = "bottom")

```




```{r}
### TOTAL NUMBER OF OBSERVATIONS BY ZONE

biodiver_sites <- read.csv("data/BiodiverCite_sites.csv", header = TRUE, sep = ';')
LUP <- read.csv("data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)
oiseaux <- read.csv("data/Oiseaux_up_to_2023.csv", header = TRUE, sep = "\t")

merged_data <- merge(biodiver_sites, LUP, by.x = "code_site", by.y = "ID", all = TRUE)

merged_data <- merge(merged_data, oiseaux, by.x = "code_site", by.y = "Code_Maille", all = TRUE)

coordinates <- st_as_sf(merged_data, coords = c("X.y", "Y"), crs = 2154)
coordinates <- st_transform(coordinates, crs = 4326)

total_observations <- coordinates %>%
  group_by(code_site) %>%
  summarise(n = n())

ggplot(data = total_observations) +
  annotation_map_tile() +  
  geom_sf(aes(size = n), color = 'blue', alpha = 0.5) +
  scale_size_continuous(range = c(2, 12), 
                        breaks = c(1, 100, 200, 500, 1000), 
                        labels = c("1", "100", "200", "500", "1000")) +
  labs(title = 'Nombre total d\'observations par zone d\'observation',
       size = 'Nombre d\'observations') +
  theme_minimal() +
  guides(size = guide_legend(override.aes = list(alpha = 0.5)))

```

```{r}
# Noms des espèces les plus observes  par catégorie de vent
merged_data$Nom_Latin <- sapply(strsplit(merged_data$Nom_Taxon_Cite, " \\| "), `[`, 1)

species_by_wind <- merged_data %>%
  group_by(Vent, Nom_Latin) %>%
  summarise(count = n()) %>%
  arrange(Vent, desc(count))

top_species_by_wind <- species_by_wind %>%
  group_by(Vent) %>%
  slice_max(order_by = count, n = 1) %>%
  ungroup()

top_species_by_wind

```

```{r}
# Noms des espèces les plus observes  par nom de site

species_by_site <- merged_data %>%
  group_by(name_site, Nom_Latin) %>%
  summarise(count = n()) %>%
  arrange(name_site, desc(count))

top_species_by_site <- species_by_site %>%
  group_by(name_site) %>%
  slice_max(order_by = count, n = 1) %>%
  ungroup()

top_species_by_site

```


```{r}
# Noms des espèces les plus observes  par temperature

species_by_temperature <- merged_data %>%
  group_by(Temperature, Nom_Latin) %>%
  summarise(count = n()) %>%
  arrange(Temperature, desc(count))

top_species_by_temperature <- species_by_temperature %>%
  group_by(Temperature) %>%
  slice_max(order_by = count, n = 1) %>%
  ungroup()

top_species_by_temperature
```


---
title: "Projet stat pour données environnementales"
author: "Louis Delignac, Baptiste Gerbouin, Théo Lavandier, Alexandre Leys, Hamad Tria"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    df_print: kable
    highlight: tango
---

```{r setup, message=FALSE, echo=FALSE}
# install.packages("tidyverse")
library(tidyverse)
library(ggplot2)
library(kableExtra)
library(sf)
library(ggspatial)
```

```{r}
oiseaux <- read.csv("data/Oiseaux_up_to_2023.csv", header = TRUE, sep = "\t")
LUP <- read.csv("data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)
```

```{r}
# CREATE A NEW COLUMN IN THE OISEAUX DATAFRAME THAT CONTAINS THE LATIN NAME OF THE BIRD
# THE LATIN NAME IS THE FIRST NAME IN THE "Nom_Taxon_Cite" COLUMN
# IF THE NAME CONTAINS A "|", THE LATIN NAME IS THE FIRST NAME BEFORE THE "|"

# Split the names
my_split <- function(array, str = " \\| ") {
  out <- rep(NA, length(array))
  for (i in 1:length(array)) {
    out[i] <- unlist(strsplit(array[i], str))[1]
  }
  return (out)
}

# Test the function
only_latin <- my_split(as.vector(oiseaux$Nom_Taxon_Cite))
length(unique(only_latin)) == length(unique(oiseaux$Code_Ref))

# Add the new column to the dataframe
oiseaux$latin <- only_latin
```

```{r}
# THE MOST FREQUENT BIRD SPECIES OBSERVED IN THE DATASET
as.data.frame(sort(table(oiseaux$latin), decreasing = TRUE)[1:10])
```

```{r}
# FREQUENCY OF BIRD SPECIES OBSERVED IN THE DATASET BY YEAR
Annee <- my_split(as.vector(oiseaux$Date), str = "-")
oiseaux$Annee <- as.factor(Annee)
as.data.frame.matrix(table(oiseaux$latin, oiseaux$Annee))
```

```{r}
# CREATE A NEW COLUMN IN THE OISEAUX DATAFRAME THAT CONTAINS THE MOS11 VALUE OF THE POINT
filter <- LUP$BufferSize == 500
LUP_500_MOS11 <- LUP[filter,c("Geometry", "ID", "X", "Y", "BufferSize", "MOS11")]
rownames(LUP_500_MOS11) <- 1:nrow(LUP_500_MOS11)
LUP_500_MOS11[, c("ID","MOS11")]

MOS11 <- rep(NA, nrow(oiseaux))
for (i in 1:nrow(oiseaux)) {
  MOS11[i] <- which(oiseaux$Code_Maille[i] == LUP_500_MOS11$ID)
}

# Add the new column to the dataframe
oiseaux$MOS11 <- LUP_500_MOS11$MOS11[MOS11]
```

```{r}
# THE NUMBER OF BIRDS OBSERVED IN EACH MOS11 AREA BY YEAR
data <- oiseaux %>%
  group_by(Code_Maille, Annee, MOS11) %>%
  select(Denombrement_min) %>% 
  summarise(sum = sum(Denombrement_min, na.rm = TRUE))

ggplot(data, aes(x=MOS11, y=sum, color=Annee)) +
      geom_point(size=2) 
```


```{r}
### TOTAL NUMBER OF OBSERVATIONS BY ZONE

biodiver_sites <- read.csv("data/BiodiverCite_sites.csv", header = TRUE, sep = ';')
LUP <- read.csv("data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)
oiseaux <- read.csv("data/Oiseaux_up_to_2023.csv", header = TRUE, sep = "\t")

merged_data <- merge(biodiver_sites, LUP, by.x = "code_site", by.y = "ID", all = TRUE)

merged_data <- merge(merged_data, oiseaux, by.x = "code_site", by.y = "Code_Maille", all = TRUE)

coordinates <- st_as_sf(merged_data, coords = c("X.y", "Y"), crs = 2154)
coordinates <- st_transform(coordinates, crs = 4326)

total_observations <- coordinates %>%
  group_by(code_site) %>%
  summarise(n = n())

ggplot(data = total_observations) +
  annotation_map_tile() +  
  geom_sf(aes(size = n), color = 'blue', alpha = 0.5) +
  scale_size_continuous(range = c(2, 12), 
                        breaks = c(1, 100, 200, 500, 1000), 
                        labels = c("1", "100", "200", "500", "1000")) +
  labs(title = 'Nombre total d\'observations par zone d\'observation',
       size = 'Nombre d\'observations') +
  theme_minimal() +
  guides(size = guide_legend(override.aes = list(alpha = 0.5)))

```





```{r}
# Noms des espèces les plus observes  par catégorie de vent
merged_data$Nom_Latin <- sapply(strsplit(merged_data$Nom_Taxon_Cite, " \\| "), `[`, 1)

species_by_wind <- merged_data %>%
  group_by(Vent, Nom_Latin) %>%
  summarise(count = n()) %>%
  arrange(Vent, desc(count))

top_species_by_wind <- species_by_wind %>%
  group_by(Vent) %>%
  slice_max(order_by = count, n = 1) %>%
  ungroup()

top_species_by_wind

```

```{r}
# Noms des espèces les plus observes  par nom de site

species_by_site <- merged_data %>%
  group_by(name_site, Nom_Latin) %>%
  summarise(count = n()) %>%
  arrange(name_site, desc(count))

top_species_by_site <- species_by_site %>%
  group_by(name_site) %>%
  slice_max(order_by = count, n = 1) %>%
  ungroup()

top_species_by_site

```




```{r}
# Noms des espèces les plus observes  par temperature

species_by_temperature <- merged_data %>%
  group_by(Temperature, Nom_Latin) %>%
  summarise(count = n()) %>%
  arrange(Temperature, desc(count))

top_species_by_temperature <- species_by_temperature %>%
  group_by(Temperature) %>%
  slice_max(order_by = count, n = 1) %>%
  ungroup()

top_species_by_temperature
```


## On doit analyser les pics de diversité par zone MOS

```{r}
# On compte le nombre d'espece differentes (espece uniques), à chaque valeur differente de la colonne MOS 11

# On regroupe les valeurs de la colonne MOS11 dans des intervalles tous les 0.1 pour faciliter le groupement par la suite. On fait ça avec le dataframe merfe_data, sans modifier la valeur MOS11 de merged data

# On crée une nouvelle colonne MOS11_interval dans le dataframe merged_data

merged_data$MOS11_interval <- cut(merged_data$MOS11, breaks = seq(0, 1, by = 0.1), include.lowest = TRUE)

# On compte le nombre d'espece unique par intervalle de MOS11

species_by_MOS11 <- merged_data %>%
  group_by(MOS11_interval) %>%
  summarise(n_species = n_distinct(Nom_Latin))

# On affiche le nombre d'espece unique par intervalle de MOS11

ggplot(data = species_by_MOS11) +
  geom_bar(aes(x = MOS11_interval, y = n_species), stat = "identity") +
  labs(title = 'Nombre d\'espèces uniques par intervalle de MOS11',
       x = 'MOS11',
       y = 'Nombre d\'espèces uniques') +
  theme_minimal()

```

```{r}
# On créer une fonction qui calcule l'indice de Shannon 

shannon_index <- function(x) {
  p <- x / sum(x)
  exp(-sum(p * log(p)))
}

# sachant qu'on le nombre d'observation dans la colonne denombrement_min, calculons l'indice de Shannon pour chaque zonne Nom_lieu

shannon_by_site <- merged_data %>%
  group_by(name_site) %>%
  summarise(shannon = shannon_index(Denombrement_min))

# Chaque lieu correspond à une valeur de MOS11, on peut donc afficher l'indice de Shannon en fonction de MOS11. On reprend donc les valeurs qu'on a calculer pour chaque lieu et on les fait correspondre à la valeur de MOS11

shannon_by_MOS11 <- merged_data %>%
  group_by(MOS11) %>%
  summarise(shannon = shannon_index(Denombrement_min))

# On drop les NA

shannon_by_MOS11 <- shannon_by_MOS11[!is.na(shannon_by_MOS11$shannon), ]

# On fait la moeyyenne des indices sur des intervalles de MOS11 tous les 0.1

shannon_by_MOS11$MOS11_interval <- cut(shannon_by_MOS11$MOS11, breaks = seq(0, 1, by = 0.1), include.lowest = TRUE)

shannon_by_MOS11 <- shannon_by_MOS11 %>%
  group_by(MOS11_interval) %>%
  summarise(shannon = mean(shannon))

# On affiche l'indice de Shannon en fonction de MOS11 avec un barchart

ggplot(data = shannon_by_MOS11) +
  geom_bar(aes(x = MOS11_interval, y = shannon), stat = "identity") +
  labs(title = 'Indice de Shannon par intervalle de MOS11',
       x = 'MOS11',
       y = 'Indice de Shannon') +
  theme_minimal()

```

```{r}
# On a observé que le pic de diversité se situe entre 0.2 et 0.4 MOS11, on va donc s'intéresser à cette zone

# On commence par load les données de caractistiques des espèces d'oiseaux

bird_data <- read_csv('data/traits-statut-IUCN-biodivercite.csv')

# On merge les données de traits avec les données de dénombrement (la colonne nom s'appelle Nom latin pour bird data)

merged_data <- left_join(merged_data, bird_data, by = c('Nom_Latin' = 'Nom latin'))





```
```{r}
merged_data <- merged_data %>%
  rename(Niveau_de_specialisation = `Niveau de spécialisation`)
```





```{r}

# Maintenant qu'on a la colonne denombrement_min_norm on peut faire la densité des oiseaux en fonction de MOS11 par rapport à cette variable

ggplot(data = merged_data) +
  geom_density(aes(x = MOS11, color = Niveau_de_specialisation), fill = 'blue', alpha = 0.5) +
  labs(title = 'Densité des oiseaux en fonction de MOS11',
       x = 'MOS11',
       y = 'Densité') +
  theme_minimal()

```

```{r}


# On refait la densité en rajoutant en poid aux observations avec la colonne denombrement_min_norm qui correspond au nombre d'observation normalisé par site

ggplot(data = merged_data) +
  geom_density(aes(x = MOS11, color = Niveau_de_specialisation, weight = Denombrement_min_norm), fill = 'blue', alpha = 0.5) +
  labs(title = 'Densité des oiseaux en fonction de MOS11',
       x = 'MOS11',
       y = 'Densité') +
  theme_minimal()

```





```{r}

merged_data$MOS11 <- as.numeric(merged_data$MOS11)

ggplot(data = merged_data, aes(x = MOS11, y = Denombrement_min_norm, color = Niveau_de_specialisation)) +
  geom_density_2d(alpha = 0.5) +
  labs(title = 'Évolution de la spécialisation en fonction de MOS11',
       x = 'MOS11',
       y = 'Pourcentage d\'observations',
       color = 'Niveau de spécialisation') +
  theme_minimal()


```


```{r}
ggplot(data = merged_data, aes(x = MOS11, y = Denombrement_min_norm, fill = Niveau_de_specialisation)) +
  geom_violin() +
  labs(title = 'Évolution de la spécialisation en fonction de MOS11',
       x = 'MOS11',
       y = 'Pourcentage d\'observations',
       fill = 'Niveau de spécialisation') +
  theme_minimal()



```




```{r}

# On fait la courbe de densité des oiseaux en fonction de MOS11, avec les oiseaux de Niveau de spécialisation qui vaut Generaliste

# On renome Niveau de spécialisation en Niveau_de_specialisation


ggplot(data = merged_data %>% filter(Niveau_de_specialisation == 'Généraliste')) +
  geom_density(aes(x = MOS11), fill = 'blue', alpha = 0.5) +
  labs(title = 'Densité des oiseaux Généralistes en fonction de MOS11',
       x = 'MOS11',
       y = 'Densité') +
  theme_minimal()

```

```{r}

ggplot(data = merged_data %>% filter(Niveau_de_specialisation == 'Bâti')) +
  geom_density(aes(x = MOS11), fill = 'blue', alpha = 0.5) +
  labs(title = 'Densité des oiseaux de type Bâti en fonction de MOS11',
       x = 'MOS11',
       y = 'Densité') +
  theme_minimal()


```

```{r}

ggplot(data = merged_data %>% filter(Niveau_de_specialisation == 'Forêt')) +
  geom_density(aes(x = MOS11), fill = 'blue', alpha = 0.5) +
  labs(title = 'Densité des oiseaux de type Forêt en fonction de MOS11',
       x = 'MOS11',
       y = 'Densité') +
  theme_minimal()

```

## On fait la maaaaaaaaaaaaaap




```{r}
oiseaux <- read.csv("data/Oiseaux_up_to_2023.csv", header = TRUE, sep = "\t")
# CREATE A NEW COLUMN IN THE OISEAUX DATAFRAME THAT CONTAINS THE LATIN NAME OF THE BIRD
my_split <- function(array, str = " \\| ") {
  out <- rep(NA, length(array))
  for (i in 1:length(array)) {
    out[i] <- unlist(strsplit(array[i], str))[1]
  }
  return (out)
}

only_latin <- my_split(as.vector(oiseaux$Nom_Taxon_Cite))
# length(unique(only_latin)) == length(unique(oiseaux$Code_Ref))

oiseaux$latin <- only_latin
oiseaux$annee <- as.numeric(substr(oiseaux$Date, 1, 4))

denombrement <- oiseaux %>%
  group_by(Code_Maille, annee, latin) %>%
  summarise(sum = sum(Denombrement_min, na.rm = TRUE), .groups = 'drop') %>%
  arrange(desc(Code_Maille))

denombrement$p <- rep(NA, nrow(denombrement))
for (i in 1:nrow(denombrement)) {
  numerator <- denombrement$sum[i]
  denominator <- 
    sum(denombrement$sum[which(denombrement$Code_Maille == denombrement$Code_Maille[i] 
                               & denombrement$annee == denombrement$annee[i])])
  denombrement$p[i] <- numerator / denominator
}

index <- denombrement %>%
  group_by(Code_Maille, annee = factor(annee)) %>%
  summarise(D1 = sum(p > 0, na.rm = TRUE), 
            D2 = exp(-sum(p*log(p))), 
            D3 = 1 / sum(p^2), .groups = 'drop') %>%
  arrange(desc(Code_Maille))

LUP <- read.csv("data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)
index$MOS11 <- rep(NA, nrow(index))
for (i in 1:nrow(index)) {
  index$MOS11[i] <- LUP$MOS11[which(index$Code_Maille[i] == LUP$ID & LUP$BufferSize == 1000)]
}

par(mfrow = c(1, 3))
ggplot(index, aes(x = MOS11, y = D1, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D1 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot(index, aes(x = MOS11, y = D2, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D1 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot(index, aes(x = MOS11, y = D3, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D1 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r}
traits <- read.csv("data/traits-statut-IUCN-biodivercite.csv", header = TRUE)



#on veut traiter la table dénombrement qu'on appelera denombrementCarte où il restera pour chaque maille et pour chaque année le top 2 des oiseaux les plus observés. On veut garder structement 2 valeurs, meme si il ya une egalité. On en prend une des deux.

denombrementCarte <- denombrement %>%
  group_by(Code_Maille, annee) %>%
  top_n(2, sum) %>%
  arrange(desc(Code_Maille), desc(sum)) %>%
  ungroup()

#maintenant dans denombrementCarte on veut ajouter les informations sur les traits des oiseaux, notamment la variable Niveau.de.spécialisation depuis traits

denombrementCarte <- denombrementCarte %>%
  left_join(traits, by = c("latin" = "Nom.latin"))

#je veux juste la variable Niveau.de.spécialisation et la variable sum

denombrementCarte <- denombrementCarte %>%
  select(Code_Maille, annee, latin, sum, Niveau.de.spécialisation)

#on veut rajouter les variables x et y de LUP dans denombrementCarte pour chaque maille

denombrementCarte <- denombrementCarte %>%
  left_join(LUP, by = c("Code_Maille" = "ID")) 

# On garde que les lignes ou BufferSize == 500
denombrementCarte <- denombrementCarte %>%
  filter(BufferSize == 500)


denombrementCarte <- denombrementCarte %>%
  select(Code_Maille, annee, latin, sum, Niveau.de.spécialisation, X, Y, MOS11)


denombrementCarte <- st_as_sf(denombrementCarte, coords = c("X", "Y"), crs = 2154)
denombrementCarte <- st_transform(denombrementCarte, crs = 4326)

#pour chaque maille, on veut qu'une ligne par maile et par année et pour le top trois, faire 3 colonnes nomlatin1, sum1, nomlatin2, sum2, nomlatin3, sum3

denombrementCarte <- denombrementCarte %>%
  group_by(Code_Maille, annee) %>%
  mutate(rank = dense_rank(-sum)) %>%
  filter(rank <= 2) %>%
  pivot_wider(names_from = rank, values_from = c(latin, sum, Niveau.de.spécialisation), names_sep = "") %>%
  select(Code_Maille, annee, latin1, sum1, Niveau.de.spécialisation1, latin2, sum2, Niveau.de.spécialisation2, MOS11, geometry) %>%
  filter(!is.na(latin1) & !is.na(latin2))

denombrementCarte$latin2 <- sapply(denombrementCarte$latin1, function(x) {
  if (is.list(x) && length(x) > 1) {
    return(x[[2]])
  } 
})

denombrementCarte$sum2 <- sapply(denombrementCarte$sum1, function(x) {
  if (is.list(x) && length(x) > 1) {
    return(x[[2]])
  } 
})

denombrementCarte$Niveau.de.spécialisation2 <- sapply(denombrementCarte$Niveau.de.spécialisation1, function(x) {
  if (is.list(x) && length(x) > 1) {
    return(x[[2]])
  } 
})

denombrementCarte$latin1 <- sapply(denombrementCarte$latin1, function(x) ifelse(is.list(x), x[[1]], x))
denombrementCarte$sum1 <- sapply(denombrementCarte$sum1, function(x) ifelse(is.list(x), x[[1]], x))
denombrementCarte$Niveau.de.spécialisation1 <- sapply(denombrementCarte$Niveau.de.spécialisation1, function(x) ifelse(is.list(x), x[[1]], x))





print(denombrementCarte)

```

```{r}

# Créer une chaîne de caractères pour les popups avec le top 3 des noms latins
denombrementCarte$popup_text <- paste0("<strong>Maille:</strong> ", denombrementCarte$Code_Maille, "<br>",
                                      "<strong>Top 1 des noms latins:</strong>", "<br>",
                                      denombrementCarte$latin1, " (", denombrementCarte$sum1, ") ", denombrementCarte$Niveau.de.spécialisation1 ,"<br>")

```




```{r}
library(leaflet)

pal <- colorNumeric("viridis", domain = denombrementCarte$MOS11)

# Créer la carte avec leaflet
leaflet(data = denombrementCarte) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircles(radius = 300, color = ~pal(MOS11), fillOpacity = 0.2, popup = ~popup_text) %>%  
  addLegend("bottomright", pal = pal, values = ~MOS11, title = "MOS11", position = "bottomright") %>%
  addScaleBar(position = "bottomleft")


```



```{r}
traits <- read.csv("data/traits-statut-IUCN-biodivercite.csv", header = TRUE)
traits

#on veut traiter la table dénombrement qu'on appelera denombrementCarte où il restera pour chaque maille et pour chaque année le top 3 des oiseaux les plus observés sans la variable p

denombrementCarte <- denombrement %>%
  group_by(Code_Maille, annee) %>%
  top_n(3, sum) %>%
  arrange(Code_Maille, annee, desc(sum)) %>%
  ungroup() %>%
  select(-p)


#on veut changer cette table pour faire apparaitre de nouvelles colonnes pour qu'il y ait : une ligne par maille et par année, et pour chaque oiseau, le nombre d'individus observés

denombrementCarte <- denombrementCarte %>%
  pivot_wider(names_from = latin, values_from = sum, values_fill = 0)

denombrementCarte

#on veut ajouter les colonnes geometry, buffer size et MOS11 à la table denombrementCarte et pas les autres

denombrementCarte <- left_join(denombrementCarte, LUP, by = c("Code_Maille" = "ID"))

#on enlève les colonnes : MOS1, MOS2, MOS3, MOS4, MOS5, MOS6, MOS7, MOS8, MOS9, MOS10, MOS12, MOS13, MOS14

denombrementCarte <- denombrementCarte %>%
  select(-c(MOS1, MOS2, MOS3, MOS4, MOS5, MOS6, MOS7, MOS8, MOS9, MOS10, MOS12, MOS13, MOS14))

# On garde que les lignes ou BufferSize == 500
denombrementCarte <- denombrementCarte %>%
  filter(BufferSize == 500)

denombrementCarte <- st_as_sf(denombrementCarte, coords = c("X", "Y"), crs = 2154)
denombrementCarte <- st_transform(denombrementCarte, crs = 4326)
```



```{r}
library(leaflet.extras)

# Créer une chaîne de caractères pour les popups avec le top trois des oiseaux ayant la plus grande valeur
denombrementCarte$popup_text <- paste0("<strong>Maille ID:</strong> ", denombrementCarte$Code_Maille, "<br>",
                                      "<strong>Année:</strong> ", denombrementCarte$annee, "<br>",
                                      "<strong>Top 3 des oiseaux:</strong>", "<br>")

# Ajouter les noms des oiseaux et leurs valeurs au popup_text pour chaque ligne
for (i in 1:nrow(denombrementCarte)) {
  top_birds <- sort(unlist(denombrementCarte[i, -c(1:8, ncol(denombrementCarte))]), decreasing = TRUE)[1:3]
  top_bird_names <- names(top_birds)
  denombrementCarte$popup_text[i] <- paste0(denombrementCarte$popup_text[i],
                                            top_bird_names[1], ": ", top_birds[1], "<br>",
                                            top_bird_names[2], ": ", top_birds[2], "<br>",
                                            top_bird_names[3], ": ", top_birds[3])
}

# Créer la carte avec leaflet
leaflet(data = denombrementCarte) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircles(radius = 300, color = ~pal(MOS11), fillOpacity = 0.2, popup = ~popup_text) %>%
  addLegend("bottomright", pal = pal, values = ~MOS11, title = "MOS11", position = "bottomright") %>%
  addScaleBar(position = "bottomleft")
```

```{r}
library(leaflet)

pal <- colorNumeric("viridis", domain = denombrementCarte$MOS11)

leaflet(data = denombrementCarte) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircles(radius = 300, color = ~pal(MOS11), fillOpacity = 0.2) %>%
  addLegend("bottomright", pal = pal, values = ~MOS11, title = "MOS11", position = "bottomright") %>%
  addScaleBar(position = "bottomleft")

# Créer la carte avec leaflet
leaflet(data = denombrementCarte) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircles(radius = 300, color = ~pal(MOS11), fillOpacity = 0.2, popup = ~popup_text) %>%  # Ajouter les popups
  addLegend("bottomright", pal = pal, values = ~MOS11, title = "MOS11", position = "bottomright") %>%
  addScaleBar(position = "bottomleft")

```


<!-- #############################HAMAD############################## -->
<!-- #############################HAMAD############################## -->
<!-- #############################HAMAD############################## -->
<!-- #############################HAMAD############################## -->
<!-- #############################HAMAD############################## -->
<!-- #############################HAMAD############################## -->
<!-- #############################HAMAD############################## -->

```{r setup, message=FALSE, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(kableExtra)
library(sf)
library(ggspatial)
library(leaflet)
library(leafpop)
library(lattice)
```

```{r}
oiseaux <- read.csv("data/Oiseaux_up_to_2023.csv", header = TRUE, sep = "\t")
# CREATE A NEW COLUMN IN THE OISEAUX DATAFRAME THAT CONTAINS THE LATIN NAME OF THE BIRD
my_split <- function(array, str = " \\| ") {
  out <- rep(NA, length(array))
  for (i in 1:length(array)) {
    out[i] <- unlist(strsplit(array[i], str))[1]
  }
  return (out)
}

only_latin <- my_split(as.vector(oiseaux$Nom_Taxon_Cite))
# length(unique(only_latin)) == length(unique(oiseaux$Code_Ref))

oiseaux$latin <- only_latin
oiseaux$annee <- as.numeric(substr(oiseaux$Date, 1, 4))

denombrement <- oiseaux %>%
  group_by(Code_Maille, annee, latin) %>%
  summarise(sum = sum(Denombrement_min, na.rm = TRUE), .groups = 'drop') %>%
  arrange(desc(Code_Maille))

denombrement$p <- rep(NA, nrow(denombrement))
for (i in 1:nrow(denombrement)) {
  numerator <- denombrement$sum[i]
  denominator <- 
    sum(denombrement$sum[which(denombrement$Code_Maille == denombrement$Code_Maille[i] 
                               & denombrement$annee == denombrement$annee[i])])
  denombrement$p[i] <- numerator / denominator
}

index <- denombrement %>%
  group_by(Code_Maille, annee = factor(annee)) %>%
  summarise(D1 = sum(p > 0, na.rm = TRUE), 
            D2 = exp(-sum(p*log(p))), 
            D3 = 1 / sum(p^2), .groups = 'drop') %>%
  arrange(desc(Code_Maille))

LUP <- read.csv("data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)
index$MOS11 <- rep(NA, nrow(index))
for (i in 1:nrow(index)) {
  index$MOS11[i] <- LUP$MOS11[which(index$Code_Maille[i] == LUP$ID & LUP$BufferSize == 500)]
}

par(mfrow = c(1, 3))
ggplot(index, aes(x = MOS11, y = D1, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D1 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot(index, aes(x = MOS11, y = D2, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D1 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot(index, aes(x = MOS11, y = D3, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D1 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r}
# changed the unmatchinng latin names to the correct ones to match alimentation
denombrement$latin[denombrement$latin == "Carduelis chloris"] <- "Chloris chloris"
denombrement$latin[denombrement$latin == "Carduelis spinus"] <- "Spinus spinus"
denombrement$latin[denombrement$latin == "Casmerodius albus"] <- "Ardea alba"
denombrement$latin[denombrement$latin == "Carduelis cannabina"] <- "Linaria cannabina"
no_info <- c("Himantopus himantopus", "Tringa ochropus", 
             "Caprimulgus europaeus", "Lanius senator", 
             "Dryocopus martius", "Emberiza calandra")

alimentation <- read.csv("traits-statut-IUCN-biodivercite.csv", header = TRUE)
denombrement$regime_alimentaire <- rep(NA, nrow(denombrement))
for (i in 1:nrow(denombrement)) {
  if (denombrement$latin[i] %in% no_info){
    denombrement$regime_alimentaire[i] <- NA
  }
  else {
    denombrement$regime_alimentaire[i] <- 
      alimentation$Régime.alimentaire[which(alimentation$Nom.latin == denombrement$latin[i])]
  }
}
denombrement$regime_alimentaire <- as.factor(denombrement$regime_alimentaire)

plot_data = function (data, title) {
    ggplot(data, aes(x="", y=sum, fill=regime_alimentaire)) +
    geom_bar(stat="identity", width=0.1) +
    coord_polar("y", start=0) +
    ggtitle(paste("Station: ", as.character(title))) +
    theme_void()
}

N <- length(unique(denombrement$Code_Maille))
p <- vector("list", length = N)

for (i in 1:N) {
    data <- denombrement[which(denombrement$Code_Maille == unique(denombrement$Code_Maille)[i]),]
    data <- data %>% group_by(regime_alimentaire) %>% summarise(sum = sum(p, na.rm = TRUE))
    p[[i]] <- plot_data(data, unique(denombrement$Code_Maille)[i])
}

coordinates <- st_as_sf(LUP, coords = c("X", "Y"), crs = 2154)
coordinates <- st_transform(coordinates, crs = 4326)
coordinates <- coordinates[coordinates$BufferSize == 500,]

# Remove the coordinates that are not in denombrement
for (i in seq_along(coordinates$ID)){
  if (!(coordinates$ID[i] %in% unique(denombrement$Code_Maille))){
    coordinates <- coordinates[-i,]
  }
}

coordinates <- coordinates[order(coordinates$ID, decreasing = TRUE),]

pal <- colorNumeric("viridis", domain = coordinates$MOS11)
leaflet(data = coordinates) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircles(radius = 300, color = ~pal(MOS11), 
             fillOpacity = 0.5, group = "pnt") %>%
  addLegend("bottomright", pal = pal, values = coordinates$MOS11, title = "MOS11") %>%
  addScaleBar(position = "bottomleft") %>% 
  addPopupGraphs(p, width = 200, height = 200, group = "pnt")
```














