---
title: "Projet stat pour données environnementales"
author: "Louis Delignac, Baptiste Gerbouin, Théo Lavandier, Alexandre Leys, Hamad Tria"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    df_print: kable
    highlight: tango
---

```{r setup, message=FALSE, echo=FALSE}
# install.packages("tidyverse")
library(tidyverse)
library(ggplot2)
library(kableExtra)
library(sf)
library(ggspatial)
```

```{r}
oiseaux <- read.csv("data/Oiseaux_up_to_2023.csv", header = TRUE, sep = "\t")
# CREATE A NEW COLUMN IN THE OISEAUX DATAFRAME THAT CONTAINS THE LATIN NAME OF THE BIRD
my_split <- function(array, str = " \\| ") {
  out <- rep(NA, length(array))
  for (i in 1:length(array)) {
    out[i] <- unlist(strsplit(array[i], str))[1]
  }
  return (out)
}

only_latin <- my_split(as.vector(oiseaux$Nom_Taxon_Cite))
# length(unique(only_latin)) == length(unique(oiseaux$Code_Ref))

oiseaux$latin <- only_latin
oiseaux$annee <- as.numeric(substr(oiseaux$Date, 1, 4))

denombrement <- oiseaux %>%
  group_by(Code_Maille, annee, latin) %>%
  summarise(sum = sum(Denombrement_min, na.rm = TRUE), .groups = 'drop') %>%
  arrange(desc(Code_Maille))

denombrement$p <- rep(NA, nrow(denombrement))
for (i in 1:nrow(denombrement)) {
  numerator <- denombrement$sum[i]
  denominator <- 
    sum(denombrement$sum[which(denombrement$Code_Maille == denombrement$Code_Maille[i] 
                               & denombrement$annee == denombrement$annee[i])])
  denombrement$p[i] <- numerator / denominator
}

index <- denombrement %>%
  group_by(Code_Maille, annee = factor(annee)) %>%
  summarise(D1 = sum(p > 0, na.rm = TRUE), 
            D2 = exp(-sum(p*log(p))), 
            D3 = 1 / sum(p^2), .groups = 'drop') %>%
  arrange(desc(Code_Maille))

LUP <- read.csv("data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)
index$MOS11 <- rep(NA, nrow(index))
for (i in 1:nrow(index)) {
  index$MOS11[i] <- LUP$MOS11[which(index$Code_Maille[i] == LUP$ID & LUP$BufferSize == 1000)]
}

par(mfrow = c(1, 3))
ggplot(index, aes(x = MOS11, y = D1, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D1 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot(index, aes(x = MOS11, y = D2, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D1 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot(index, aes(x = MOS11, y = D3, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D1 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r}
traits <- read.csv("data/traits-statut-IUCN-biodivercite.csv", header = TRUE)



#on veut traiter la table dénombrement qu'on appelera denombrementCarte où il restera pour chaque maille et pour chaque année le top 2 des oiseaux les plus observés. On veut garder structement 2 valeurs, meme si il ya une egalité. On en prend une des deux.

denombrementCarte <- denombrement %>%
  group_by(Code_Maille, annee) %>%
  top_n(2, sum) %>%
  arrange(desc(Code_Maille), desc(sum)) %>%
  ungroup()

#maintenant dans denombrementCarte on veut ajouter les informations sur les traits des oiseaux, notamment la variable Niveau.de.spécialisation depuis traits

denombrementCarte <- denombrementCarte %>%
  left_join(traits, by = c("latin" = "Nom.latin"))

#je veux juste la variable Niveau.de.spécialisation et la variable sum

denombrementCarte <- denombrementCarte %>%
  select(Code_Maille, annee, latin, sum, Niveau.de.spécialisation)

#on veut rajouter les variables x et y de LUP dans denombrementCarte pour chaque maille

denombrementCarte <- denombrementCarte %>%
  left_join(LUP, by = c("Code_Maille" = "ID")) 

# On garde que les lignes ou BufferSize == 500
denombrementCarte <- denombrementCarte %>%
  filter(BufferSize == 500)


denombrementCarte <- denombrementCarte %>%
  select(Code_Maille, annee, latin, sum, Niveau.de.spécialisation, X, Y, MOS11)


denombrementCarte <- st_as_sf(denombrementCarte, coords = c("X", "Y"), crs = 2154)
denombrementCarte <- st_transform(denombrementCarte, crs = 4326)

#pour chaque maille, on veut qu'une ligne par maile et par année et pour le top trois, faire 3 colonnes nomlatin1, sum1, nomlatin2, sum2, nomlatin3, sum3

denombrementCarte <- denombrementCarte %>%
  group_by(Code_Maille, annee) %>%
  mutate(rank = dense_rank(-sum)) %>%
  filter(rank <= 2) %>%
  pivot_wider(names_from = rank, values_from = c(latin, sum, Niveau.de.spécialisation), names_sep = "") %>%
  select(Code_Maille, annee, latin1, sum1, Niveau.de.spécialisation1, latin2, sum2, Niveau.de.spécialisation2, MOS11, geometry) %>%
  filter(!is.na(latin1) & !is.na(latin2))

denombrementCarte$latin2 <- sapply(denombrementCarte$latin1, function(x) {
  if (is.list(x) && length(x) > 1) {
    return(x[[2]])
  } 
})

denombrementCarte$sum2 <- sapply(denombrementCarte$sum1, function(x) {
  if (is.list(x) && length(x) > 1) {
    return(x[[2]])
  } 
})

denombrementCarte$Niveau.de.spécialisation2 <- sapply(denombrementCarte$Niveau.de.spécialisation1, function(x) {
  if (is.list(x) && length(x) > 1) {
    return(x[[2]])
  } 
})

denombrementCarte$latin1 <- sapply(denombrementCarte$latin1, function(x) ifelse(is.list(x), x[[1]], x))
denombrementCarte$sum1 <- sapply(denombrementCarte$sum1, function(x) ifelse(is.list(x), x[[1]], x))
denombrementCarte$Niveau.de.spécialisation1 <- sapply(denombrementCarte$Niveau.de.spécialisation1, function(x) ifelse(is.list(x), x[[1]], x))





print(denombrementCarte)

```

```{r}

# Créer une chaîne de caractères pour les popups avec le top 3 des noms latins
denombrementCarte$popup_text <- paste0("<strong>Maille:</strong> ", denombrementCarte$Code_Maille, "<br>",
                                      "<strong>Top 1 des noms latins:</strong>", "<br>",
                                      denombrementCarte$latin1, " (", denombrementCarte$sum1, ") ", denombrementCarte$Niveau.de.spécialisation1 ,"<br>")

```




```{r}
library(leaflet)

pal <- colorNumeric("viridis", domain = denombrementCarte$MOS11)

# Créer la carte avec leaflet
leaflet(data = denombrementCarte) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircles(radius = 300, color = ~pal(MOS11), fillOpacity = 0.2, popup = ~popup_text) %>%  
  addLegend("bottomright", pal = pal, values = ~MOS11, title = "MOS11", position = "bottomright") %>%
  addScaleBar(position = "bottomleft")


```



```{r}
traits <- read.csv("data/traits-statut-IUCN-biodivercite.csv", header = TRUE)
traits

#on veut traiter la table dénombrement qu'on appelera denombrementCarte où il restera pour chaque maille et pour chaque année le top 3 des oiseaux les plus observés sans la variable p

denombrementCarte <- denombrement %>%
  group_by(Code_Maille, annee) %>%
  top_n(3, sum) %>%
  arrange(Code_Maille, annee, desc(sum)) %>%
  ungroup() %>%
  select(-p)


#on veut changer cette table pour faire apparaitre de nouvelles colonnes pour qu'il y ait : une ligne par maille et par année, et pour chaque oiseau, le nombre d'individus observés

denombrementCarte <- denombrementCarte %>%
  pivot_wider(names_from = latin, values_from = sum, values_fill = 0)

denombrementCarte

#on veut ajouter les colonnes geometry, buffer size et MOS11 à la table denombrementCarte et pas les autres

denombrementCarte <- left_join(denombrementCarte, LUP, by = c("Code_Maille" = "ID"))

#on enlève les colonnes : MOS1, MOS2, MOS3, MOS4, MOS5, MOS6, MOS7, MOS8, MOS9, MOS10, MOS12, MOS13, MOS14

denombrementCarte <- denombrementCarte %>%
  select(-c(MOS1, MOS2, MOS3, MOS4, MOS5, MOS6, MOS7, MOS8, MOS9, MOS10, MOS12, MOS13, MOS14))

# On garde que les lignes ou BufferSize == 500
denombrementCarte <- denombrementCarte %>%
  filter(BufferSize == 500)

denombrementCarte <- st_as_sf(denombrementCarte, coords = c("X", "Y"), crs = 2154)
denombrementCarte <- st_transform(denombrementCarte, crs = 4326)
```



```{r}
library(leaflet.extras)

# Créer une chaîne de caractères pour les popups avec le top trois des oiseaux ayant la plus grande valeur
denombrementCarte$popup_text <- paste0("<strong>Maille ID:</strong> ", denombrementCarte$Code_Maille, "<br>",
                                      "<strong>Année:</strong> ", denombrementCarte$annee, "<br>",
                                      "<strong>Top 3 des oiseaux:</strong>", "<br>")

# Ajouter les noms des oiseaux et leurs valeurs au popup_text pour chaque ligne
for (i in 1:nrow(denombrementCarte)) {
  top_birds <- sort(unlist(denombrementCarte[i, -c(1:8, ncol(denombrementCarte))]), decreasing = TRUE)[1:3]
  top_bird_names <- names(top_birds)
  denombrementCarte$popup_text[i] <- paste0(denombrementCarte$popup_text[i],
                                            top_bird_names[1], ": ", top_birds[1], "<br>",
                                            top_bird_names[2], ": ", top_birds[2], "<br>",
                                            top_bird_names[3], ": ", top_birds[3])
}

# Créer la carte avec leaflet
leaflet(data = denombrementCarte) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircles(radius = 300, color = ~pal(MOS11), fillOpacity = 0.2, popup = ~popup_text) %>%
  addLegend("bottomright", pal = pal, values = ~MOS11, title = "MOS11", position = "bottomright") %>%
  addScaleBar(position = "bottomleft")
```

```{r}
library(leaflet)

pal <- colorNumeric("viridis", domain = denombrementCarte$MOS11)

leaflet(data = denombrementCarte) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircles(radius = 300, color = ~pal(MOS11), fillOpacity = 0.2) %>%
  addLegend("bottomright", pal = pal, values = ~MOS11, title = "MOS11", position = "bottomright") %>%
  addScaleBar(position = "bottomleft")

# Créer la carte avec leaflet
leaflet(data = denombrementCarte) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircles(radius = 300, color = ~pal(MOS11), fillOpacity = 0.2, popup = ~popup_text) %>%  # Ajouter les popups
  addLegend("bottomright", pal = pal, values = ~MOS11, title = "MOS11", position = "bottomright") %>%
  addScaleBar(position = "bottomleft")

```


