---
title: "Theo_branch"
output: html_document
date: "2024-04-17"
---

```{r setup, message=FALSE, echo=FALSE}
# install.packages("tidyverse")
library(tidyverse)
library(ggplot2)
library(kableExtra)
library(sf)
library(ggspatial)
library(leaflet)
```




```{r}
oiseaux <- read.csv("data/Oiseaux_up_to_2023.csv", header = TRUE, sep = "\t")
# CREATE A NEW COLUMN IN THE OISEAUX DATAFRAME THAT CONTAINS THE LATIN NAME OF THE BIRD
my_split <- function(array, str = " \\| ") {
  out <- rep(NA, length(array))
  for (i in 1:length(array)) {
    out[i] <- unlist(strsplit(array[i], str))[1]
  }
  return (out)
}

only_latin <- my_split(as.vector(oiseaux$Nom_Taxon_Cite))
# length(unique(only_latin)) == length(unique(oiseaux$Code_Ref))

oiseaux$latin <- only_latin
oiseaux$annee <- as.numeric(substr(oiseaux$Date, 1, 4))

denombrement <- oiseaux %>%
  group_by(Code_Maille, annee, latin) %>%
  summarise(sum = sum(Denombrement_min, na.rm = TRUE), .groups = 'drop') %>%
  arrange(desc(Code_Maille))

denombrement$p <- rep(NA, nrow(denombrement))
for (i in 1:nrow(denombrement)) {
  numerator <- denombrement$sum[i]
  denominator <- 
    sum(denombrement$sum[which(denombrement$Code_Maille == denombrement$Code_Maille[i] 
                               & denombrement$annee == denombrement$annee[i])])
  denombrement$p[i] <- numerator / denominator
}

index <- denombrement %>%
  group_by(Code_Maille, annee = factor(annee)) %>%
  summarise(D1 = sum(p > 0, na.rm = TRUE), 
            D2 = exp(-sum(p*log(p))), 
            D3 = 1 / sum(p^2), .groups = 'drop') %>%
  arrange(desc(Code_Maille))

LUP <- read.csv("data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)
index$MOS11 <- rep(NA, nrow(index))
for (i in 1:nrow(index)) {
  index$MOS11[i] <- LUP$MOS11[which(index$Code_Maille[i] == LUP$ID & LUP$BufferSize == 1000)]
}

par(mfrow = c(1, 3))
ggplot(index, aes(x = MOS11, y = D1, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D1 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot(index, aes(x = MOS11, y = D2, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D1 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot(index, aes(x = MOS11, y = D3, color = annee)) +
  geom_point(size = 2) +
  labs(title = 'D1 en fonction de MOS11',
       x = 'MOS11',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r}
traits <- read.csv("data/traits-statut-IUCN-biodivercite.csv", header = TRUE)
cite <- read.csv("data/BiodiverCite_sites.csv", header = TRUE, sep=";")

#on veut traiter la table dénombrement qu'on appelera denombrementCarte où il restera pour chaque maille et pour chaque année le top 3 des oiseaux les plus observés sans la variable p

denombrementCarte <- denombrement %>%
  group_by(Code_Maille, annee) %>%
  top_n(3, sum) %>%
  arrange(Code_Maille, annee, desc(sum)) %>%
  ungroup() %>%
  select(-p)


#on veut changer cette table pour faire apparaitre de nouvelles colonnes pour qu'il y ait : une ligne par maille et par année, et pour chaque oiseau, le nombre d'individus observés

denombrementCarte <- denombrementCarte %>%
  pivot_wider(names_from = latin, values_from = sum, values_fill = 0)


#on veut ajouter les colonnes geometry, buffer size et MOS11 à la table denombrementCarte et pas les autres

denombrementCarte <- left_join(denombrementCarte, LUP, by = c("Code_Maille" = "ID"))

#on enlève les colonnes : MOS1, MOS2, MOS3, MOS4, MOS5, MOS6, MOS7, MOS8, MOS9, MOS10, MOS12, MOS13, MOS14

denombrementCarte <- denombrementCarte %>%
  select(-c(MOS1, MOS2, MOS3, MOS4, MOS5, MOS6, MOS7, MOS8, MOS9, MOS10, MOS12, MOS13, MOS14))

# On garde que les lignes ou BufferSize == 500
denombrementCarte <- denombrementCarte %>%
  filter(BufferSize == 500)

denombrementCarte <- st_as_sf(denombrementCarte, coords = c("X", "Y"), crs = 2154)
denombrementCarte <- st_transform(denombrementCarte, crs = 4326)

# On garde seuelement les valeurs ou annee = 2018

denombrementCarte <- denombrementCarte %>%
  filter(annee == 2023)

denombrementCarte

```

```{r}

library(leaflet.extras)

# On garder que les colonnes qui nous intéressent, cad code_site et Nom_lieu

cite <- read.csv("data/BiodiverCite_sites.csv", header = TRUE, sep=";")
cite <- cite %>%
  select(code_site, Nom_lieu)

#On join les deux tables cite et denombrementCarte

denombrementCarte <- left_join(denombrementCarte, cite, by = c("Code_Maille" = "code_site"))

# Créer une chaîne de caractères pour les popups avec le top trois des oiseaux ayant la plus grande valeur
denombrementCarte$popup_text <- paste0("<strong>Maille:</strong> ", denombrementCarte$Nom_lieu, "<br>",
                                      "<strong>Année:</strong> ", denombrementCarte$annee, "<br>",
                                      "<strong>Top 3 des oiseaux:</strong>", "<br>")

dataframe <- as.data.frame(denombrementCarte)
dataframe

# On enleve les colonnes Code_Maille, annee, BufferSize, MOS11, Geometry, geometry
dataframe <- dataframe %>%
  select(-c(Code_Maille, annee, BufferSize, MOS11, Geometry, geometry, Nom_lieu))

# Ajouter les noms des oiseaux et leurs valeurs au popup_text pour chaque ligne
for (i in 1:nrow(dataframe)) {
  top_birds <- sort(unlist(dataframe[i, -c(ncol(dataframe))]), decreasing = TRUE)[1:3]
  top_bird_names <- names(top_birds)
  denombrementCarte$popup_text[i] <- paste0(denombrementCarte$popup_text[i],
                                            top_bird_names[1], ": ", top_birds[1], " - ", traits[which(traits$Nom.latin == top_bird_names[1]), "Niveau.de.spécialisation"], "<br>",
                                            top_bird_names[2], ": ", top_birds[2], " - ", traits[which(traits$Nom.latin == top_bird_names[2]), "Niveau.de.spécialisation"], "<br>",
                                            top_bird_names[3], ": ", top_birds[3], " - ", traits[which(traits$Nom.latin == top_bird_names[3]), "Niveau.de.spécialisation"])
}

pal <- colorNumeric("viridis", domain = denombrementCarte$MOS11)


leaflet(data = denombrementCarte) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircles(radius = 300, color = ~pal(MOS11), fillOpacity = 0.2, popup = ~popup_text) %>%
  addLegend("bottomright", pal = pal, values = ~MOS11, title = "MOS11", position = "bottomright") %>%
  addScaleBar(position = "bottomleft")



```




```{r}
# changed the unmatchinng latin names to the correct ones to match alimentation
denombrement$latin[denombrement$latin == "Carduelis chloris"] <- "Chloris chloris"
denombrement$latin[denombrement$latin == "Carduelis spinus"] <- "Spinus spinus"
denombrement$latin[denombrement$latin == "Casmerodius albus"] <- "Ardea alba"
denombrement$latin[denombrement$latin == "Carduelis cannabina"] <- "Linaria cannabina"
no_info <- c("Himantopus himantopus", "Tringa ochropus", 
             "Caprimulgus europaeus", "Lanius senator", 
             "Dryocopus martius", "Emberiza calandra")

alimentation <- read.csv("data/traits-statut-IUCN-biodivercite.csv", header = TRUE)
denombrement$regime_alimentaire <- rep(NA, nrow(denombrement))
for (i in 1:nrow(denombrement)) {
  if (denombrement$latin[i] %in% no_info){
    denombrement$regime_alimentaire[i] <- NA
  }
  else {
    denombrement$regime_alimentaire[i] <- 
      alimentation$Régime.alimentaire[which(alimentation$Nom.latin == denombrement$latin[i])]
  }
}
denombrement$regime_alimentaire <- as.factor(denombrement$regime_alimentaire)

plot_data = function (data, title) {
    ggplot(data, aes(x="", y=sum, fill=regime_alimentaire)) +
    geom_bar(stat="identity", width=0.1) +
    coord_polar("y", start=0) +
    ggtitle(paste("Station: ", as.character(title))) +
    theme_void()
}

cite <- cite %>%
  select(code_site, Nom_lieu)

#On join les deux tables cite et denombrementCarte

denombrement <- left_join(denombrement, cite, by = c("Code_Maille" = "code_site"))

N <- length(unique(denombrement$Code_Maille))
p <- vector("list", length = N)

for (i in 1:N) {
    data <- denombrement[which(denombrement$Code_Maille == unique(denombrement$Code_Maille)[i]),]
    data <- data %>% group_by(regime_alimentaire) %>% summarise(sum = sum(p, na.rm = TRUE))
    p[[i]] <- plot_data(data, unique(denombrement$Nom_lieu)[i])
}

coordinates <- st_as_sf(LUP, coords = c("X", "Y"), crs = 2154)
coordinates <- st_transform(coordinates, crs = 4326)
coordinates <- coordinates[coordinates$BufferSize == 500,]

# Remove the coordinates that are not in denombrement
for (i in seq_along(coordinates$ID)){
  if (!(coordinates$ID[i] %in% unique(denombrement$Code_Maille))){
    coordinates <- coordinates[-i,]
  }
}

coordinates <- coordinates[order(coordinates$ID, decreasing = TRUE),]

pal <- colorNumeric("viridis", domain = coordinates$MOS11)
leaflet(data = coordinates) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircles(radius = 300, color = ~pal(MOS11), 
             fillOpacity = 0.5, group = "pnt") %>%
  addLegend("bottomright", pal = pal, values = coordinates$MOS11, title = "MOS11") %>%
  addScaleBar(position = "bottomleft") %>% 
  addPopupGraphs(p, width = 200, height = 200, group = "pnt")
```



```{r}
denombrement$Nidification <- rep(NA, nrow(denombrement))
for (i in 1:nrow(denombrement)) {
  if (denombrement$latin[i] %in% no_info){
    denombrement$Nidification[i] <- NA
  }
  else {
    denombrement$Nidification[i] <- 
      alimentation$Nidification[which(alimentation$Nom.latin == denombrement$latin[i])]
  }
}
denombrement$Nidification <- as.factor(denombrement$Nidification)

plot_data = function (data, title) {
    ggplot(data, aes(x="", y=sum, fill=Nidification)) +
    geom_bar(stat="identity", width=0.1) +
    coord_polar("y", start=0) +
    ggtitle(paste("Station: ", as.character(title))) +
    theme_void()
}

#On join les deux tables cite et denombrementCarte

N <- length(unique(denombrement$Code_Maille))
p <- vector("list", length = N)

for (i in 1:N) {
    data <- denombrement[which(denombrement$Code_Maille == unique(denombrement$Code_Maille)[i]),]
    data <- data %>% group_by(Nidification) %>% summarise(sum = sum(p, na.rm = TRUE))
    p[[i]] <- plot_data(data, unique(denombrement$Nom_lieu)[i])
}

coordinates <- st_as_sf(LUP, coords = c("X", "Y"), crs = 2154)
coordinates <- st_transform(coordinates, crs = 4326)
coordinates <- coordinates[coordinates$BufferSize == 500,]

# Remove the coordinates that are not in denombrement
for (i in seq_along(coordinates$ID)){
  if (!(coordinates$ID[i] %in% unique(denombrement$Code_Maille))){
    coordinates <- coordinates[-i,]
  }
}

coordinates <- coordinates[order(coordinates$ID, decreasing = TRUE),]

pal <- colorNumeric("viridis", domain = coordinates$MOS11)
leaflet(data = coordinates) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircles(radius = 300, color = ~pal(MOS11), 
             fillOpacity = 0.5, group = "pnt") %>%
  addLegend("bottomright", pal = pal, values = coordinates$MOS11, title = "MOS11") %>%
  addScaleBar(position = "bottomleft") %>% 
  addPopupGraphs(p, width = 200, height = 200, group = "pnt")
```

```{r}

# Maintenant on va faire un datframe qui calcule les distances de toues les stations code_maille avec le centre ville, en considérant que le centre ville est PeyBerland 

# On donne la cordonnée de PeyBerland (latitude et longitude) afin de calculer les distances par la suite avec sf
# lat = 44.838168 et long = -0.578803

PeyBerland <- data.frame("Latitude" = 44.838168, "Longitude" = -0.578803)

# On convertit les coordonnées de PeyBerland en sf

PeyBerland <- st_as_sf(PeyBerland, coords = c("Longitude", "Latitude"), crs = 4326)

# On va créer un dataframe qui contient les coordonnées de toutes les stations code_maille

coordinates <- st_as_sf(LUP, coords = c("X", "Y"), crs = 2154)

# On va transformer les coordonnées de 2154 à 4326

coordinates <- st_transform(coordinates, crs = 4326)

# On va calculer les distances entre les stations et le centre ville PeyBerland

coordinates$Distance <- st_distance(coordinates, PeyBerland)

```


```{r}
## Analyse de diversité par rapport à MOS11 et par année

denombrement <- oiseaux %>%
  group_by(Code_Maille, annee, latin) %>%
  summarise(sum = sum(Denombrement_min, na.rm = TRUE), .groups = 'drop') %>%
  arrange(desc(Code_Maille))

denombrement$p <- rep(NA, nrow(denombrement))
for (i in 1:nrow(denombrement)) {
  numerator <- denombrement$sum[i]
  denominator <- 
    sum(denombrement$sum[which(denombrement$Code_Maille == denombrement$Code_Maille[i] 
                               & denombrement$annee == denombrement$annee[i])])
  denombrement$p[i] <- numerator / denominator
}

index <- denombrement %>%
  group_by(Code_Maille, annee = factor(annee)) %>%
  summarise(D1 = sum(p > 0, na.rm = TRUE), 
            D2 = exp(-sum(p*log(p))), 
            D3 = 1 / sum(p^2), .groups = 'drop') %>%
  arrange(desc(Code_Maille))

LUP <- read.csv("data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)
index$Distance <- rep(NA, nrow(index))
for (i in 1:nrow(index)) {
  index$Distance[i] <- coordinates$Distance[which(index$Code_Maille[i] == coordinates$ID & coordinates$BufferSize == 500)]
}

par(mfrow = c(1, 3))
ggplot(index, aes(x = Distance, y = D1, color = as.factor(annee))) +
  geom_point(size = 2) +
  geom_smooth(method = "auto", se = TRUE, color = "black", alpha = 0.2) +
  labs(title = 'D1 en fonction de la distance au centre-ville',
       x = 'Distance',
       y = 'D1') +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot(index, aes(x = Distance, y = D2, color = as.factor(annee))) +
  geom_point(size = 2) +
  geom_smooth(method = "auto", se = TRUE, color = "black", alpha = 0.2) +
  labs(title = 'D2 en fonction de la distance au centre-ville',
       x = 'Distance',
       y = 'D2') +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot(index, aes(x = Distance, y = D3, color = as.factor(annee))) +
  geom_point(size = 2) +
  geom_smooth(method = "auto", se = TRUE, color = "black", alpha = 0.2) +
  labs(title = 'D3 en fonction de la distance au centre-ville',
       x = 'Distance',
       y = 'D3') +
  theme_minimal() +
  theme(legend.position = "bottom")
```


```{r}
unique_year <- unique(LUP_birds_obs[, "Year"])
unique_year <- unique_year[order(unique_year)]

ids <- c("Année", unique_year)
for (year in unique_year) {
  ids <- c(ids, paste0(year, paste0(" - MOS", 1:14)))
}

for (year in unique_year) {
  for (mos in paste0("MOS", 1:14)) {
    for (specie in birds_info[, "Nom.latin"]) {
      ids <- c(ids, paste0(year, paste0(paste0(" - ", mos), paste0(" - ", specie))))
    }
  }
}

labels <- c("Année", unique_year, rep(paste0("MOS", 1:14), times = length(unique_year)))
labels <- c(labels, rep(birds_info[, "Nom.latin"], times = 14 * length(unique_year)))

parents <- c("", rep("Année", times = length(unique_year)), rep(unique_year, each = 14))
for (year in unique_year) {
  parents <- c(parents, paste0(year, rep(paste0(" - MOS", 1:14), each = length(birds_info[, "Nom.latin"]))))
}

buffer_sizes <- c(350, 500, 1000, 1500, 2000)
df <- data.frame()

for (buffer_size in buffer_sizes) {
  values <- c(c(length(unique_year) * 14000, rep(14000, times = length(unique_year))), rep(1000, times = length(unique_year) * 14))
  for (year in unique_year) {
    for (mos in paste0("MOS", 1:14)) {
      for (specie in birds_info[, "Nom.latin"]) {
        tmp <- LUP_birds_obs[LUP_birds_obs["Year"] == year & LUP_birds_obs["Latin"] == specie & LUP_birds_obs["BufferSize"] == buffer_size, ]
        values <- c(values, sum(tmp[mos] * tmp["Sum"]))
      }
      tail_values <- values[(1 + length(values) - length(birds_info[, "Nom.latin"])):length(values)]
      values[(1 + length(values) - length(birds_info[, "Nom.latin"])):length(values)] <- tail_values / sum(tail_values) * 1000
    }
  }

  is_nan_values <- !is.na(values) & values != 0
  current_ids <- paste0(paste0(buffer_size, " - "), ids)
  current_parents <- paste0(paste0(buffer_size, " - "), parents)
  current_parents[1] <- ""
  print(current_parents[1:20])

  tmp_df <- data.frame(
    bufferSize = buffer_size,
    ids = current_ids[is_nan_values],
    labels = labels[is_nan_values],
    parents = current_parents[is_nan_values],
    values = values[is_nan_values]
  )
  df <- rbind(df, tmp_df)
}
```

```{r}
df %>% plot_ly(
  ids = ~ids,
  labels = ~labels,
  parents = ~parents,
  values = ~values,
  type = "sunburst",
  branchvalues = "total",
  maxdepth = 2,
  hoverinfo = "label+percent entry",
  transforms = list(
    list(
      type = "filter",
      target = ~bufferSize,
      operation = "=",
      value = buffer_sizes
    )
  )
) %>% layout(
  updatemenus = list(
    list(
      x = 1.5,
      y = 1.2,
      type = "dropdown",
      active = 0,
      buttons = lapply(
        buffer_sizes, function(x) {
          list(
            method = "restyle",
            args = list("transforms[0].value", x),
            label = x
          )
        }
      )
    )
  )
)
```

```{r}
library(plotly)
library(crosstalk)
library(dplyr)

df_shared <- SharedData$new(df)

# Créer le filtre
filter <- bscols(
  filter_select("bufferSize", "Filter par bufferSize", df_shared, ~bufferSize, multiple = FALSE),
  widths = c(12)
)

# Créer le graphique sunburst
sunburst <- plot_ly(
  data = df_shared,
  ids = ~ids,
  labels = ~labels,
  parents = ~parents,
  values = ~values,
  type = "sunburst",
  branchvalues = "total",
  maxdepth = 2,
  hoverinfo = "label+percent+value"
)

# Afficher le filtre et le graphique côte à côte
bscols(list(filter, sunburst))
```